using System.Collections.Generic;

namespace RsDocGenerator
{
    public static class CodeInspectionHelpers
    {
        static CodeInspectionHelpers()
        {
            ExternalInspectionLinks = new Dictionary<string, string>
            {
                {"CSharpWarnings::CS0282", "https://learn.microsoft.com/en-us/dotnet/csharp/misc/cs0282"},
                {"CSharpWarnings::CS0108", "https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/cs0108"},
                {"CSharpWarnings::CS0109", "https://learn.microsoft.com/en-us/dotnet/csharp/misc/cs0109"},
                {"CSharpWarnings::CS0162", "https://learn.microsoft.com/en-us/dotnet/csharp/misc/cs0162"},
                {"CSharpWarnings::CS0183", "https://learn.microsoft.com/en-us/dotnet/csharp/misc/cs0183"},
                {"CSharpWarnings::CS0184", "https://learn.microsoft.com/en-us/dotnet/csharp/misc/cs0184"},
                {"CSharpWarnings::CS0197", "https://learn.microsoft.com/en-us/dotnet/csharp/misc/cs0197"},
                {"CSharpWarnings::CS0252", "https://learn.microsoft.com/en-us/dotnet/csharp/misc/cs0252"},
                {"CSharpWarnings::CS0420", "https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/cs0420"},
                {"CSharpWarnings::CS0465", "https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/cs0465"},
                {"CSharpWarnings::CS0469", "https://learn.microsoft.com/en-us/dotnet/csharp/misc/cs0469"},
                {"CSharpWarnings::CS0612", "https://learn.microsoft.com/en-us/dotnet/csharp/misc/cs0469"},
                {"CSharpWarnings::CS0618", "https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/cs0618"},
                {"CSharpWarnings::CS0628", "https://learn.microsoft.com/en-us/dotnet/csharp/misc/cs0628"},
                {"CSharpWarnings::CS0642", "https://learn.microsoft.com/en-us/dotnet/csharp/misc/cs0642"},
                {"CSharpWarnings::CS0657", "https://learn.microsoft.com/en-us/dotnet/csharp/misc/cs0657"},
                {"CSharpWarnings::CS0658", "https://learn.microsoft.com/en-us/dotnet/csharp/misc/cs0658"},
                {"CSharpWarnings::CS0659", "https://learn.microsoft.com/en-us/dotnet/csharp/misc/cs0659"},
                {"CSharpWarnings::CS0660", "https://learn.microsoft.com/en-us/dotnet/csharp/misc/cs0660"},
                {"CSharpWarnings::CS0665", "https://learn.microsoft.com/en-us/dotnet/csharp/misc/cs0665"},
                {"CSharpWarnings::CS0672", "https://learn.microsoft.com/en-us/dotnet/csharp/misc/cs0672"},
                {"CSharpWarnings::CS0693", "https://learn.microsoft.com/en-us/dotnet/csharp/misc/cs0693"},
                {"CSharpWarnings::CS1030", "https://learn.microsoft.com/en-us/dotnet/csharp/misc/cs1030"},
                {"CSharpWarnings::CS1058", "https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/cs1058"},
                {"CSharpWarnings::CS1522", "https://learn.microsoft.com/en-us/dotnet/csharp/misc/cs1522"},
                {"CSharpWarnings::CS1570", "https://learn.microsoft.com/en-us/dotnet/csharp/misc/cs1570"},
                {"CSharpWarnings::CS1571", "https://learn.microsoft.com/en-us/dotnet/csharp/misc/cs1571"},
                {"CSharpWarnings::CS1573", "https://learn.microsoft.com/en-us/dotnet/csharp/misc/cs1573"},
                {"CSharpWarnings::CS1574", "https://learn.microsoft.com/en-us/dotnet/csharp/misc/cs1574"},
                {"CSharpWarnings::CS1580", "https://learn.microsoft.com/en-us/dotnet/csharp/misc/cs1580"},
                {"CSharpWarnings::CS1584", "https://learn.microsoft.com/en-us/dotnet/csharp/misc/cs1584"},
                {"CSharpWarnings::CS1587", "https://learn.microsoft.com/en-us/dotnet/csharp/misc/cs1587"},
                {"CSharpWarnings::CS1589", "https://learn.microsoft.com/en-us/dotnet/csharp/misc/cs1589"},
                {"CSharpWarnings::CS1590", "https://learn.microsoft.com/en-us/dotnet/csharp/misc/cs1590"},
                {"CSharpWarnings::CS1591", "https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/cs1591"},
                {"CSharpWarnings::CS1592", "https://learn.microsoft.com/en-us/dotnet/csharp/misc/cs1592"},
                {"CSharpWarnings::CS1710", "https://learn.microsoft.com/en-us/dotnet/csharp/misc/cs1710"},
                {"CSharpWarnings::CS1712", "https://learn.microsoft.com/en-us/dotnet/csharp/misc/cs1712"},
                {"CSharpWarnings::CS1717", "https://learn.microsoft.com/en-us/dotnet/csharp/misc/cs1717"},
                {"CSharpWarnings::CS1723", "https://learn.microsoft.com/en-us/dotnet/csharp/misc/cs1723"},
                {"CSharpWarnings::CS1911", "https://learn.microsoft.com/en-us/dotnet/csharp/misc/cs1911"},
                {"CSharpWarnings::CS1957", "https://learn.microsoft.com/en-us/dotnet/csharp/misc/cs1957"},
                {"CSharpWarnings::CS4014", "https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/cs4014"},
                {"CSharpWarnings::CS0078", "https://learn.microsoft.com/en-us/dotnet/csharp/misc/cs0078"},
                  {"CSharpWarnings::CS9196", "https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/ref-modifiers-errors#reference-variable-restrictions"},
                  {"CSharpWarnings::CS9200", "https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/ref-modifiers-errors#reference-variable-restrictions"},
                  {"CSharpWarnings::CS9191", "https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/ref-modifiers-errors#reference-variables-require-a-referent"},
                  {"CSharpWarnings::CS9192", "https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/ref-modifiers-errors#reference-variables-require-a-referent"},
                  {"CSharpWarnings::CS9193", "https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/ref-modifiers-errors#reference-variables-require-a-referent"},
                  {"CSharpWarnings::CS9195", "https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/ref-modifiers-errors#reference-variables-require-a-referent"},
                  {"CSharpWarnings::CS9159", "https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/source-generator-errors#signature-mismatch"},
                  {"CSharpWarnings::CS9158", "https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/source-generator-errors#signature-mismatch"},
                  {"CSharpWarnings::CS9154", "https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/source-generator-errors#signature-mismatch"},
                  {"CSharpWarnings::CS9124", "https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/constructor-errors#primary-constructor-declaration"},
                  {"CSharpWarnings::CS9179", "https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/constructor-errors#primary-constructor-declaration"},
                  {"CSharpWarnings::CS9107", "https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/constructor-errors#primary-constructor-declaration"},
                  {"CSharpWarnings::CS9182", "https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/inline-array-errors#conversions-to-span"},
                  {"CSharpWarnings::CS9183", "https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/inline-array-errors#conversions-to-span"},
                  {"CSharpWarnings::CS9181", "https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/inline-array-errors#element-access"},
                  {"CSharpWarnings::CS9184", "https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/inline-array-errors#inline-array-declaration"},
                  {"CSharpWarnings::CS0728", "https://learn.microsoft.com/en-us/dotnet/csharp/misc/cs0728"},
                  {"CSharpWarnings::CS9100", "https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/lambda-expression-errors#lambda-expression-delegate-type"},
                  {"CSharpWarnings::CS9099", "https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/lambda-expression-errors#lambda-expression-delegate-type"},
                  {"CSharpWarnings::CS9086", "https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/ref-modifiers-errors#ref-safety-violations"},
                  {"CSharpWarnings::CS9093", "https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/ref-modifiers-errors#ref-safety-violations"},
                  {"CSharpWarnings::CS9097", "https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/ref-modifiers-errors#ref-safety-violations"},
                  {"CSharpWarnings::CS9085", "https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/ref-modifiers-errors#ref-safety-violations"},
                  {"CSharpWarnings::CS9092", "https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/ref-modifiers-errors#ref-safety-violations"},
                  {"CSharpWarnings::CS9087", "https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/ref-modifiers-errors#ref-safety-violations"},
                  {"CSharpWarnings::CS9094", "https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/ref-modifiers-errors#ref-safety-violations"},
                  {"CSharpWarnings::CS9089", "https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/ref-modifiers-errors#ref-safety-violations"},
                  {"CSharpWarnings::CS9095", "https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/ref-modifiers-errors#ref-safety-violations"},
                  {"CSharpWarnings::CS9091", "https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/ref-modifiers-errors#ref-safety-violations"},
                  {"CSharpWarnings::CA2252", "https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca2252"},
                  {"CSharpWarnings::CS0458", "https://learn.microsoft.com/en-us/dotnet/csharp/misc/cs0458"},
                  {"CSharpWarnings::CS0472", "https://learn.microsoft.com/en-us/dotnet/csharp/misc/cs0472"},
                  {"CSharpWarnings::CS8981", "https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/warning-waves#cs8981---the-type-name-only-contains-lower-cased-ascii-characters"},
                  {"CSharpWarnings::CS0464", "https://learn.microsoft.com/en-us/dotnet/csharp/misc/cs0464"},
                  {"CSharpWarnings::CS8073", "https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/warning-waves#cs8073---the-result-of-the-expression-is-always-false-or-true"},
                  {"CSharpWarnings::CS8971", "https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/lambda-expression-errors#syntax-limitations-in-lambda-expressions"},
                  {"CSharpWarnings::CS8847", "https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/nullable-warnings#exhaustive-switch-expression"},
                  {"CSharpWarnings::CS8655", "https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/nullable-warnings#exhaustive-switch-expression"},
                  {"CSharpWarnings::CS0675", "https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/cs0675"},
                  {"CSharpWarnings::CS0652", "https://learn.microsoft.com/en-us/dotnet/csharp/misc/cs0652"},
                  {"CSharpWarnings::CS7023", "https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/warning-waves#cs7023---a-static-type-is-used-in-an-is-or-as-expression"},
                  {"CSharpWarnings::CS8892", "https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/warning-waves#cs8892---method-will-not-be-used-as-an-entry-point-because-a-synchronous-entry-point-method-was-found"},
                  {"CSharpWarnings::CS8819", "https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/nullable-warnings#mismatch-in-nullability-declaration"},
                  {"CSharpWarnings::CS8768", "https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/nullable-warnings#mismatch-in-nullability-declaration"},
                  {"CSharpWarnings::CS8766", "https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/nullable-warnings#mismatch-in-nullability-declaration"},
                  {"CSharpWarnings::CS8764", "https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/nullable-warnings#mismatch-in-nullability-declaration"},
                  {"CSharpWarnings::CS8769", "https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/nullable-warnings#mismatch-in-nullability-declaration"},
                  {"CSharpWarnings::CS8767", "https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/nullable-warnings#mismatch-in-nullability-declaration"},
                  {"CSharpWarnings::CS8765", "https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/nullable-warnings#mismatch-in-nullability-declaration"},
                  {"CSharpWarnings::CS8633", "https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/nullable-warnings#mismatch-in-nullability-declaration"},
                  {"CSharpWarnings::CS8643", "https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/nullable-warnings#mismatch-in-nullability-declaration"},
                  {"CSharpWarnings::CS8644", "https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/nullable-warnings#mismatch-in-nullability-declaration"},
                  {"CSharpWarnings::CS8634", "https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/nullable-warnings#mismatch-in-nullability-declaration"},
                  {"CSharpWarnings::CS8631", "https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/nullable-warnings#mismatch-in-nullability-declaration"},
                  {"CSharpWarnings::CS8714", "https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/nullable-warnings#mismatch-in-nullability-declaration"},
                  {"CSharpWarnings::CS8667", "https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/nullable-warnings#mismatch-in-nullability-declaration"},
                  {"CSharpWarnings::CS8645", "https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/nullable-warnings#mismatch-in-nullability-declaration"},
                  {"CSharpWarnings::CS8620", "https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/nullable-warnings#mismatch-in-nullability-declaration"},
                  {"CSharpWarnings::CS8616", "https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/nullable-warnings#mismatch-in-nullability-declaration"},
                  {"CSharpWarnings::CS8613", "https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/nullable-warnings#mismatch-in-nullability-declaration"},
                  {"CSharpWarnings::CS8609", "https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/nullable-warnings#mismatch-in-nullability-declaration"},
                  {"CSharpWarnings::CS8621", "https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/nullable-warnings#mismatch-in-nullability-declaration"},
                  {"CSharpWarnings::CS8619", "https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/nullable-warnings#mismatch-in-nullability-declaration"},
                  {"CSharpWarnings::CS8615", "https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/nullable-warnings#mismatch-in-nullability-declaration"},
                  {"CSharpWarnings::CS8612", "https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/nullable-warnings#mismatch-in-nullability-declaration"},
                  {"CSharpWarnings::CS8608", "https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/nullable-warnings#mismatch-in-nullability-declaration"},
                  {"CSharpWarnings::CS8622", "https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/nullable-warnings#mismatch-in-nullability-declaration"},
                  {"CSharpWarnings::CS8617", "https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/nullable-warnings#mismatch-in-nullability-declaration"},
                  {"CSharpWarnings::CS8614", "https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/nullable-warnings#mismatch-in-nullability-declaration"},
                  {"CSharpWarnings::CS8610", "https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/nullable-warnings#mismatch-in-nullability-declaration"},
                  {"CSharpWarnings::CS8611", "https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/nullable-warnings#mismatch-in-nullability-declaration"},
                  {"CSharpWarnings::CS8624", "https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/nullable-warnings#mismatch-in-nullability-declaration"},
                  {"CSharpWarnings::CS8824", "https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/nullable-warnings#code-doesnt-match-attribute-declaration"},
                  {"CSharpWarnings::CS8825", "https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/nullable-warnings#code-doesnt-match-attribute-declaration"},
                  {"CSharpWarnings::CS8607", "https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/nullable-warnings#code-doesnt-match-attribute-declaration"},
                  {"CSharpWarnings::CS8770", "https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/nullable-warnings#code-doesnt-match-attribute-declaration"},
                  {"CSharpWarnings::CS8763", "https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/nullable-warnings#code-doesnt-match-attribute-declaration"},
                  {"CSharpWarnings::CS8776", "https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/nullable-warnings#code-doesnt-match-attribute-declaration"},
                  {"CSharpWarnings::CS8775", "https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/nullable-warnings#code-doesnt-match-attribute-declaration"},
                  {"CSharpWarnings::CS8774", "https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/nullable-warnings#code-doesnt-match-attribute-declaration"},
                  {"CSharpWarnings::CS8777", "https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/nullable-warnings#code-doesnt-match-attribute-declaration"},
                  {"CSharpWarnings::CS8602", "https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/nullable-warnings#possible-dereference-of-null"},
                  {"CSharpWarnings::CS8670", "https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/nullable-warnings#possible-dereference-of-null"},
                  {"CSharpWarnings::CS8762", "https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/nullable-warnings#nonnullable-reference-not-initialized"},
                  {"CSharpWarnings::CS8618", "https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/nullable-warnings#nonnullable-reference-not-initialized"},
                  {"CSharpWarnings::CS8597", "https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/nullable-warnings#possible-null-assigned-to-a-nonnullable-reference"},
                  {"CSharpWarnings::CS8605", "https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/nullable-warnings#possible-null-assigned-to-a-nonnullable-reference"},
                  {"CSharpWarnings::CS8625", "https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/nullable-warnings#possible-null-assigned-to-a-nonnullable-reference"},
                  {"CSharpWarnings::CS8600", "https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/nullable-warnings#possible-null-assigned-to-a-nonnullable-reference"},
                  {"CSharpWarnings::CS8629", "https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/nullable-warnings#possible-null-assigned-to-a-nonnullable-reference"},
                  {"CSharpWarnings::CS8604", "https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/nullable-warnings#possible-null-assigned-to-a-nonnullable-reference"},
                  {"CSharpWarnings::CS8601", "https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/nullable-warnings#possible-null-assigned-to-a-nonnullable-reference"},
                  {"CSharpWarnings::CS8603", "https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/nullable-warnings#possible-null-assigned-to-a-nonnullable-reference"},
                  {"CSharpWarnings::CS8509", "https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/pattern-matching-warnings"},
                  {"CSharpWarnings::CS1711", "https://learn.microsoft.com/en-us/dotnet/csharp/misc/cs1711"},
                  {"CSharpWarnings::CS1574,CS1584,CS1581,CS1580", "CSharpWarnings_CS1574_CS1584_CS1581_CS1580"},
                {"CSharpWarnings::CS0108,CS0114", "CSharpWarnings_CS0108_CS0114"},
                {"CSharpWarnings::CS0660,CS0661", "CSharpWarnings_CS0660_CS0661"},
                {"CSharpWarnings::CS0252,CS0253", "CSharpWarnings_CS0252_CS0253"},
                {"VBWarnings::BC42105,BC42106,BC42107", "VBWarnings_BC42105_BC42106_BC42107"},
                {"VBWarnings::BC42353,BC42354,BC42355", "VBWarnings_BC42353_BC42354_BC42355"},
                {"VBWarnings::BC400005", "https://learn.microsoft.com/en-us/dotnet/visual-basic/misc/bc40005"},
                {"VBWarnings::BC42358", "https://learn.microsoft.com/en-us/dotnet/visual-basic/language-reference/error-messages/bc42358"},
                {"VBWarnings::BC42025", "https://learn.microsoft.com/en-us/dotnet/visual-basic/language-reference/error-messages/bc42025"},
                {"VBWarnings::BC40056", "https://learn.microsoft.com/en-us/dotnet/visual-basic/language-reference/error-messages/namespace-or-type-specified-in-the-project-level-imports-qualifiedelementname"},
                {"VBWarnings::BC42016", "https://learn.microsoft.com/en-us/dotnet/visual-basic/misc/bc42016"},
                {"VBWarnings::BC40008", "https://learn.microsoft.com/en-us/dotnet/visual-basic/language-reference/error-messages/elementname-is-obsolete-visual-basic-warning"},
                {"VBWarnings::BC42104", "https://learn.microsoft.com/en-us/dotnet/visual-basic/language-reference/error-messages/variable-variablename-is-used-before-it-has-been-assigned-a-value"},
                {"VBWarnings::BC42304", "https://learn.microsoft.com/en-us/dotnet/visual-basic/misc/bc42304"},
                {"VBWarnings::BC42309", "https://learn.microsoft.com/en-us/dotnet/visual-basic/misc/bc42309"},
                {"VBWarnings::BC42322", "https://learn.microsoft.com/en-us/dotnet/visual-basic/misc/bc42322"}
            };

            PsiLanguagesByCategoryNames = new Dictionary<string, string>
            {
                {"CSharpErrors", "CSHARP"},
                {"WebConfig Errors", "Web.Config"},
                {"XAML Errors", "XAML"},
                {"HtmlErrors", "HTML"},
                {"XMLErrors", "XML"},
                {"AsxxErrors", "ASXX"},
                {"AspErrors", "ASPX"},
                {"CppCompilerErrors", "CPP"},
                {"VBErrors", "VBASIC"},
                {"JScriptErrors", "JAVA_SCRIPT"},
                {"Razor Errors", "Razor"},
                {"Razor Warnings", "Razor"},
                {"Razor Info", "Razor"},
            };
        }

        public static Dictionary<string, string> ExternalInspectionLinks { get; set; }
        public static Dictionary<string, string> PsiLanguagesByCategoryNames { get; set; }

        public static string TryGetStaticHref(string inspectionId)
        {
            if (ExternalInspectionLinks.ContainsKey(inspectionId))
                return ExternalInspectionLinks[inspectionId];
            if (inspectionId.Contains("::"))
                return "NO_LINK";
            return inspectionId;
        }
    }
}